import { writeFile, mkdtemp } from 'fs/promises';
import { tmpdir } from 'os';
import { join } from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

export async function recordTerminal(analysis, repoPath) {
  // Check if VHS is installed
  try {
    await execAsync('which vhs');
  } catch {
    throw new Error(
      'VHS is not installed. Install it with: brew install vhs (macOS) or see https://github.com/charmbracelet/vhs'
    );
  }

  // Create temp directory for output
  const tempDir = await mkdtemp(join(tmpdir(), 'repovideo-record-'));
  const tapeFile = join(tempDir, 'demo.tape');
  const outputFile = join(tempDir, 'demo.mp4');

  // Generate VHS tape file
  const tape = generateTape(analysis, repoPath, outputFile);
  await writeFile(tapeFile, tape);

  // Run VHS
  try {
    await execAsync(`vhs ${tapeFile}`, { 
      timeout: 120000,
      cwd: repoPath 
    });
  } catch (error) {
    throw new Error(`VHS recording failed: ${error.message}`);
  }

  return outputFile;
}

function generateTape(analysis, repoPath, outputFile) {
  const lines = [
    `# Generated by RepoVideo`,
    `Output "${outputFile}"`,
    ``,
    `Set FontSize 18`,
    `Set Width 1280`,
    `Set Height 720`,
    `Set Theme "Dracula"`,
    `Set Padding 20`,
    `Set Framerate 30`,
    ``,
    `# Start recording`,
    `Hide`,
    `Type "cd ${repoPath}"`,
    `Enter`,
    `Sleep 500ms`,
    `Show`,
    ``
  ];

  // Add commands with realistic typing
  for (const command of analysis.commands) {
    lines.push(`Type "${command}"`);
    lines.push(`Sleep 500ms`);
    lines.push(`Enter`);
    lines.push(`Sleep 3s`);
    lines.push(``);
  }

  // Final pause
  lines.push(`Sleep 2s`);

  return lines.join('\n');
}
